// <auto-generated />
namespace EntityFrameworkExamples.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class product_Description : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(product_Description));
        
        string IMigrationMetadata.Id
        {
            get { return "201907241044440_product_Description"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
